import React from 'react';
import { render as ReactDOMRender } from 'react-dom';
import registerServiceWorker from './registerServiceWorker';
import './css/heartsApp.css';
import './card_hand.svg';
import HeartsApp from './heartsApp';
import heartsCreateStore from './heartsCreateStore';
import * as heartsActions from './actions';

const heartsStore = heartsCreateStore();
const render = () => ReactDOMRender(<HeartsApp store={heartsStore} />, document.getElementById('root'));
heartsStore.subscribe(render);
heartsStore.dispatch(heartsActions.addPlayer("Bob", "AI"));
heartsStore.dispatch(heartsActions.addPlayer("Doug", "AI"));
heartsStore.dispatch(heartsActions.addPlayer("Bill", "AI"));
heartsStore.dispatch(heartsActions.addPlayer("Tim", "Human"));
heartsStore.dispatch(heartsActions.deal());
let firstPlayerID = heartsStore.getState().players[0].id;
heartsStore.dispatch(heartsActions.playCard(firstPlayerID, heartsStore.getState().players[0].playerHand[0]));
render();
registerServiceWorker();
